language: c

addons:
 apt:
  packages:
   - libpcap0.8-dev

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc
  allow_failures:
    - os: osx
      compiler: clang

script:
  - ./autogen.sh
  - ./configure
  - make

sudo: false
